<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CTUFDT2" ignored="1" name="Submit Order Tests" tests="2" failures="1" timestamp="27 Nov 2022 12:15:31 GMT" time="45.747" errors="0">
  <testcase name="SubmitOrder" time="16.01" classname="learningspace.tests.SubmitOrderTest"/>
  <testcase name="SubmitOrder" time="15.556" classname="learningspace.tests.SubmitOrderTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at learningspace.tests.SubmitOrderTest.SubmitOrder(SubmitOrderTest.java:37)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- SubmitOrder -->
  <testcase name="VerifyOrder" time="0.0" classname="learningspace.tests.SubmitOrderTest">
    <ignored/>
  </testcase> <!-- VerifyOrder -->
</testsuite> <!-- Submit Order Tests -->
